apiVersion: apps/v1
kind: Deployment
metadata:
  name: KUB-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KUB
  template:
    metadata:
      labels:
        app: KUB
    spec:
      containers:
      - name: kub
        image: kubrn.azurecr.io/kub:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: kub
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: KUB